language: node_js
node_js:
- 8.12.0
notifications:
  email:
    on_success: always
deploy:
  - provider: npm
    skip_cleanup: true
    email: rapid.build@yahoo.com
    api_key: $NPM_TOKEN
    on:
      tags: true