language: node_js
node_js:
  - 6.11.0
notifications:
  email:
    on_success: always
before_script:
  - npm link
deploy:
  - provider: npm
    skip_cleanup: true
    email: jyounce@yahoo.com
    api_key:
      secure: JRR+gdB4nXCzt/M0/Q5jlgcFP+iPsEhZJnn36MK9N749BWMl31tdgmhdoQESpeJZtLY/T/zaISYkHXCiIegiW8HFFdEorCvbNxgTaowETeYjIZj62g3FBmM1A8zGeEgKA6a2Oo4H9nvqCD9r/wbHgiZeVT4L6O8BtlU0n+HGzeypWCfr1lU/ToznjMTdnffOL/4Wfh4D5TfwiFT/HMnUtTebWFZH0TaYMtdcBh3QloEgoDddXQ+MUQNC1lZjeXNR4ua+a9zhBpmzWNTbgnHH2ShD5y6bEsAqVtoExUsA7aDtE3Eimcl4XVldQeXX8H84M7nf409izXjO80Ww5iyO8Ca2f/5N1sJ1QAwyi7NFWfGEppzW6c4zRZ/1tRHSP1ca7VTqQTFPcE0mulx/BgolV+G2xHJaVMGulYD7wQFFwaPQxPQHtoNaYMVFBlYYA3FXiSJvGMuDtNwbUf/8XGhRcE1noVJDH7KvDmKouxci0kyeH0s6sMlPF813uQgZlxsb3Fidu9bkD58oOnn8zK/+Q2iI9/nWSIRR8F4pRxJhuVm7sjDgk/fzObkRwuHcegvQ41ISQaX1idXGWdYPnuCTT9IgEtPUOijk1u61zt9ckJwjESjVYVz4Y8NcmFVD7KLNtgoUdfgMIm751l3ZxMveS4ajmzR7K59tMco4f2EznZg=
    on:
      tags: true